Add support for creating groups
groupme-js/node-groupme pull request #91
Opened 2022-05-11 06:06 UTC by striker4150

Resolves #7.

2022-05-11 06:09 UTC, thewilloftheshadow commented
Test failure was due to the fact it was running on a fork with no access to the testing account

2022-05-11 18:04 UTC, not-so-smart commented
> Test failure was due to the fact it was running on a fork with no access to the testing account

yeah lol this is a bit of a problem, I feel like we should make it so that either the tests don't run on forks at all, or make it so that org members can manually run the tests on a pr after checking out the code if that's possible

2022-05-11 19:32 UTC, not-so-smart requested changes
Thanks for the PR! See comments, and remember to add `PostGroupBody` and `PostGroupResponse` to the type import from `groupme-api-types` on line 1.

2022-05-12 02:10 UTC, striker4150 commented
I made the changes as requested. Let me know if you have any other suggestions.

2022-05-12 02:25 UTC, not-so-smart requested changes
looks great! one more tiny code quality/formatting change just for consistency and I think this is ready to merge 👍

2022-05-12 02:25 UTC, not-so-smart commented on src/managers/GroupManager.ts
> +        const res = await this.client.rest.api<PostGroupResponse>('POST', 'groups', { body: reqBody })
can you rename `reqBody` to just `body` and then use shorthand notation here? just for consistency with implementations of other API methods
```suggestion
        const res = await this.client.rest.api<PostGroupResponse>('POST', 'groups', { body })
```

2022-05-12 03:39 UTC, not-so-smart approved these changes
Looks good! Thanks for contributing 😊👍

2022-05-12 03:46 UTC, not-so-smart commented
before we merge this, @thewilloftheshadow can you double check why the tests failed? I approved the actions to run but either the auth token didn't get shared or some test genuinely didn't pass. I also couldn't access the logs from this run for some reason, maybe you can get them somehow.

2022-05-12 03:54 UTC, thewilloftheshadow commented
Yeah I can see the logs, it's from how I have them setup, I need to change some things. You can go ahead and merge

2022-05-12 03:55 UTC, merged